# Generated by Django 4.1 on 2023-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='title of article'),
        ),
    ]
